<?php
$HOSTNAME="localhost";//SERVIDOR
$USERNAME="root";		//USUARIO
$PASSWORD="";		//CONTRASEÑA RECUERDA LA CONTRASEÑA QUE TU ESCRIBISTE EN LA INSTALACION
$DATABASE="pingosdb";	//BASE DE DATOS
$PUERTO="3310"; //PUERTO
?>
